### ISSUE TITLE
troubleshooting Zepplin Notebook

### ISSUE THREAD

**Issue by vap0rtranz** [sabre1041/iot-ocp#40]
How do I troubleshoot the Zepplin graphs?  Pods are running in Openshift.  My imported Notebook displays no graphs and instead displays an "ERROR" in the far right column.  There are 2 rows: Counter Readings, and Number of Readings.  It's almost like the Notebook import via JSON isn't working (I've tried importing a couple times)

I can send you a screenshot directly.

**Comment by vap0rtranz** [comment]
The pod logs from software sensor shows measurements:

```
2017-06-23 21:42:26.847  INFO 1 --- [pool-1-thread-3] c.redhat.examples.iot.SchedulerManager   : Current Measure [vibration]: 17.466737997480223
2017-06-23 21:42:26.863 INFO 1 --- [pool-1-thread-2] c.redhat.examples.iot.SchedulerManager : Current Measure [gps]: 40.13125799999991|-73.8858410000001
```

**Comment by vap0rtranz** [comment]
OK I found the Zeppelin logs (/opt/zeppelin/storage/logs) in the pod.  Below is the NPE thrown when importing the JSON from this repo as a Notebook in the GUI:                                                                                                                                                                                                                              
                                                                                                                                                                                                                                     
```
 INFO [2017-06-23 22:02:36,982] ({qtp1018547642-15} NotebookServer.java[sendNote]:433) - New operation from 172.17.0.1 : 48128 : anonymous : GET_NOTE : 2CMBSHC61                                                                    
 INFO [2017-06-23 22:02:47,852] ({pool-1-thread-10} SchedulerFactory.java[jobStarted]:131) - Job paragraph_1498255353044_400989075 started by scheduler org.apache.zeppelin.interpreter.remote.RemoteInterpretershared_session2004000
289                                                                                                                                                                                                                                  
 INFO [2017-06-23 22:02:47,852] ({pool-1-thread-10} Paragraph.java[jobRun]:252) - run paragraph 20161001-183325_618919355 using psql org.apache.zeppelin.interpreter.LazyOpenInterpreter@27bc8c7a                                    
 INFO [2017-06-23 22:02:47,887] ({pool-1-thread-10} NotebookServer.java[afterStatusChange]:1150) - Job 20161001-183325_618919355 is finished                                                                                         
 INFO [2017-06-23 22:02:47,907] ({pool-1-thread-10} SchedulerFactory.java[jobFinished]:137) - Job paragraph_1498255353044_400989075 finished by scheduler org.apache.zeppelin.interpreter.remote.RemoteInterpretershared_session20040
00289                                                                                                                                                                                                                                
 INFO [2017-06-23 22:02:47,908] ({pool-1-thread-1} SchedulerFactory.java[jobStarted]:131) - Job paragraph_1498255353044_400989075 started by scheduler org.apache.zeppelin.interpreter.remote.RemoteInterpretershared_session20040002
89                                                                                                                                                                                                                                   
 INFO [2017-06-23 22:02:47,909] ({pool-1-thread-1} Paragraph.java[jobRun]:252) - run paragraph 20161001-183432_1739764842 using psql org.apache.zeppelin.interpreter.LazyOpenInterpreter@27bc8c7a                                    
 INFO [2017-06-23 22:02:47,926] ({pool-1-thread-1} NotebookServer.java[afterStatusChange]:1150) - Job 20161001-183432_1739764842 is finished                                                                                         
 INFO [2017-06-23 22:02:47,940] ({pool-1-thread-1} SchedulerFactory.java[jobFinished]:137) - Job paragraph_1498255353044_400989075 finished by scheduler org.apache.zeppelin.interpreter.remote.RemoteInterpretershared_session200400
0289                                                                                                                                                                                                                                 
ERROR [2017-06-23 22:03:00,003] ({DefaultQuartzScheduler_Worker-7} JobRunShell.java[run]:211) - Job note.2CK4DAZWT threw an unhandled Exception:                                                                                     
java.lang.NullPointerException                                                                                                                                                                                                       
        at org.apache.zeppelin.notebook.Notebook$CronJob.execute(Notebook.java:641)                                                                                                                                                  
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)                                                                                                                                                                     
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)                                                                                                                                             
ERROR [2017-06-23 22:03:00,003] ({DefaultQuartzScheduler_Worker-7} QuartzScheduler.java[schedulerError]:2425) - Job (note.2CK4DAZWT threw an exception.                                                                              
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]                                                                                                              
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)                                                                                                                                                                     
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)                                                                                                                                             
Caused by: java.lang.NullPointerException                                                                                                                                                                                            
        at org.apache.zeppelin.notebook.Notebook$CronJob.execute(Notebook.java:641)                                                                                                                                                  
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)                                                                                                                                                                     
        ... 1 more    
```

**Comment by ishuverma** [comment]
What interpreters do you see in the list? Click on the gear on top right to see the Interpreters

**Comment by vap0rtranz** [comment]
@ishuverma just had the same thought this morning -- that the Interpreter was wrong -- and now I remember that last stage of the init.sh looked amiss when building this out.  So I just deleted my Minishift, restarted from scratch, and this problem isn't there.  So maybe the config of the Interpreter borked in my previous buildout.  Anyways, case closed.

BTW: the --retry is really awesome on the init.sh!
